version: '3'
services:
  ldap:
    build:
      context: .
      dockerfile: docker/ldap.Dockerfile
    container_name: ldap
    environment:
      LDAP_TLS: 'true'
      LDAP_TLS_CRT_FILENAME: 'fullchain.pem'
      LDAP_TLS_KEY_FILENAME: 'privkey.pem'
      LDAP_TLS_CA_CRT_FILENAME: 'fullchain.pem'
      LDAP_ORGANISATION: "TemplateLdap"
      LDAP_DOMAIN: "ldap"
      LDAP_BASE_DN: "dc=ldap"
      LDAP_ADMIN_PASSWORD: "test"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    hostname: ldap
    image: osixia/openldap:stable-amd64
    ports:
    - "389:389"
    - "636:636"
    tty: true
    volumes:
    - ./data:/etc/ldap/slapd.d

  ldap-ui:
    container_name: ldap-ui
    depends_on:
      - ldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    image: osixia/phpldapadmin:latest
    ports:
    - "8080:80"