version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/ldap.Dockerfile
    container_name: server.com
    environment:
      LDAP_TLS: 'true'
      LDAP_TLS_CRT_FILENAME: 'fullchain.pem'
      LDAP_TLS_KEY_FILENAME: 'privkey.pem'
      LDAP_TLS_CA_CRT_FILENAME: 'fullchain.pem'
      LDAP_ORGANISATION: "TemplateLdap"
      LDAP_DOMAIN: "server"
      LDAP_BASE_DN: "dc=server"
      LDAP_ADMIN_PASSWORD: "test"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    hostname: server.com
    image: osixia/openldap:stable-amd64
    ports:
    - 389
    - 636
    tty: true
    volumes:
    - ./data:/etc/ldap/slapd.d

  client:
    build:
      context: .
      dockerfile: docker/ldap.Dockerfile
    container_name: client
    depends_on:
      - server
    environment:
    - CMD_TEST=ldapwhoami -x -D "cn=admin,dc=server" -h server -w test
    - PHPLDAPADMIN_LDAP_HOSTS=server
    - PHPLDAPADMIN_HTTPS=false
    image: osixia/phpldapadmin:0.9.0